#!/usr/bin/env python3
"""Validate the brand palette and rebuild every brand artifact.

This is the gate for a [Design] ticket (CHANGE_MANAGEMENT.md §7). A green run is a
real statement: the palette parses, every required token exists, every colour is a
valid hex, and every declared contrast pair meets its WCAG ratio.

    python3 brands/scripts/build_all.py           # validate and write artifacts
    python3 brands/scripts/build_all.py --check   # validate; fail if artifacts are stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

BRANDS_DIR = Path(__file__).resolve().parent.parent
PALETTE_PATH = BRANDS_DIR / "tokens" / "palette.json"
DIST_DIR = BRANDS_DIR / "dist"

HEX_PATTERN = re.compile(r"^#[0-9A-Fa-f]{6}$")

REQUIRED_COLORS = {
    "primary",
    "secondary",
    "tertiary",
    "accent",
    "background",
    "surface",
    "surface-muted",
    "border",
    "text-heading",
    "text-body",
    "text-muted",
    "text-on-primary",
}

REQUIRED_SEMANTIC = {
    "state-approved",
    "state-pending",
    "state-rejected",
    "state-draft",
    "health-green",
    "health-amber",
    "health-red",
}


def relative_luminance(hex_color: str) -> float:
    channels = []
    for offset in (1, 3, 5):
        value = int(hex_color[offset : offset + 2], 16) / 255
        channels.append(value / 12.92 if value <= 0.03928 else ((value + 0.055) / 1.055) ** 2.4)
    red, green, blue = channels
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue


def contrast_ratio(foreground: str, background: str) -> float:
    lighter, darker = sorted(
        (relative_luminance(foreground), relative_luminance(background)), reverse=True
    )
    return (lighter + 0.05) / (darker + 0.05)


def validate(palette: dict) -> list[str]:
    problems: list[str] = []

    for theme_key in ("light", "dark"):
        theme = palette.get("themes", {}).get(theme_key)
        if theme is None:
            problems.append(f"themes.{theme_key} is missing")
            continue

        colors = theme.get("colors", {})
        for missing in sorted(REQUIRED_COLORS - colors.keys()):
            problems.append(f"themes.{theme_key}.colors.{missing} is missing")
        for name, value in colors.items():
            if not HEX_PATTERN.match(str(value)):
                problems.append(f"themes.{theme_key}.colors.{name} is not a #RRGGBB hex: {value!r}")

        semantic = palette.get("semantic", {}).get(theme_key, {})
        for missing in sorted(REQUIRED_SEMANTIC - semantic.keys()):
            problems.append(f"semantic.{theme_key}.{missing} is missing")
        for name, value in semantic.items():
            if not HEX_PATTERN.match(str(value)):
                problems.append(f"semantic.{theme_key}.{name} is not a #RRGGBB hex: {value!r}")

        for requirement in palette.get("contrast_requirements", []):
            foreground = colors.get(requirement["fg"])
            background = colors.get(requirement["bg"])
            if not (
                foreground
                and background
                and HEX_PATTERN.match(str(foreground))
                and HEX_PATTERN.match(str(background))
            ):
                continue
            ratio = contrast_ratio(foreground, background)
            if ratio < requirement["min_ratio"]:
                problems.append(
                    f"{theme_key}: {requirement['fg']} on {requirement['bg']} is "
                    f"{ratio:.2f}:1, below the required {requirement['min_ratio']}:1"
                )

    return problems


def _declarations(prefix: str, items: dict) -> list[str]:
    return [f"  --{prefix}-{name}: {value};" for name, value in items.items()]


def render_css(palette: dict) -> str:
    light = palette["themes"]["light"]["colors"]
    dark = palette["themes"]["dark"]["colors"]
    light_semantic = palette["semantic"]["light"]
    dark_semantic = palette["semantic"]["dark"]
    typography = palette["typography"]

    lines = [
        "/* Generated by brands/scripts/build_all.py — do not edit by hand.",
        f"   Source: brands/tokens/palette.json (v{palette['version']}) */",
        "",
        ":root {",
        f"  --font-sans: {typography['font-sans']};",
        f"  --font-mono: {typography['font-mono']};",
    ]
    lines += [f"  --text-{name}: {value};" for name, value in typography["scale"].items()]
    lines += _declarations("space", palette["space"])
    lines += _declarations("radius", palette["radius"])
    lines.append("")
    lines.append(f"  /* {palette['themes']['light']['name']} — light is the default */")
    lines += _declarations("color", light)
    lines += _declarations("color", light_semantic)
    lines.append("}")
    lines.append("")
    lines.append(f"/* {palette['themes']['dark']['name']} */")
    lines.append('[data-theme="dark"] {')
    lines += _declarations("color", dark)
    lines += _declarations("color", dark_semantic)
    lines.append("}")
    lines.append("")
    lines.append("@media (prefers-color-scheme: dark) {")
    lines.append('  :root:not([data-theme="light"]) {')
    lines += [f"  {line}" for line in _declarations("color", dark)]
    lines += [f"  {line}" for line in _declarations("color", dark_semantic)]
    lines.append("  }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_flat_tokens(palette: dict) -> str:
    flat: dict[str, str] = {}
    for theme_key in ("light", "dark"):
        for name, value in palette["themes"][theme_key]["colors"].items():
            flat[f"color.{theme_key}.{name}"] = value
        for name, value in palette["semantic"][theme_key].items():
            flat[f"color.{theme_key}.{name}"] = value
    for name, value in palette["typography"]["scale"].items():
        flat[f"text.{name}"] = value
    for name, value in palette["space"].items():
        flat[f"space.{name}"] = value
    for name, value in palette["radius"].items():
        flat[f"radius.{name}"] = value
    return json.dumps(flat, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate only; exit non-zero if committed artifacts are stale",
    )
    args = parser.parse_args()

    try:
        palette = json.loads(PALETTE_PATH.read_text())
    except FileNotFoundError:
        print(f"FAIL  {PALETTE_PATH} not found", file=sys.stderr)
        return 1
    except json.JSONDecodeError as error:
        print(f"FAIL  {PALETTE_PATH} is not valid JSON: {error}", file=sys.stderr)
        return 1

    problems = validate(palette)
    if problems:
        print(f"FAIL  {len(problems)} palette problem(s):", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    artifacts = {
        DIST_DIR / "tokens.css": render_css(palette),
        DIST_DIR / "tokens.json": render_flat_tokens(palette),
    }

    if args.check:
        stale = [path for path, content in artifacts.items() if _read(path) != content]
        if stale:
            for path in stale:
                print(f"FAIL  {path.relative_to(BRANDS_DIR.parent)} is stale", file=sys.stderr)
            print("      run: python3 brands/scripts/build_all.py", file=sys.stderr)
            return 1
        print("OK    palette valid, artifacts current")
        return 0

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in artifacts.items():
        path.write_text(content)
        print(f"OK    wrote {path.relative_to(BRANDS_DIR.parent)}")

    print(f"OK    palette valid ({len(REQUIRED_COLORS)} colours x 2 themes, contrast checked)")
    return 0


def _read(path: Path) -> str | None:
    try:
        return path.read_text()
    except FileNotFoundError:
        return None


if __name__ == "__main__":
    raise SystemExit(main())
