"""approver ordering

Existing memberships default to position 1, which is exactly the single-approver chain
EPIC 0 already ran.

Revision ID: 14feabd416d5
Revises: 2729c746402b
Create Date: 2026-08-23 15:21:50.964443

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14feabd416d5"
down_revision: str | Sequence[str] | None = "2729c746402b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        # server_default: existing memberships need a position, and 1 matches the single-approver
        # behaviour EPIC 0 shipped.
        batch_op.add_column(
            sa.Column("approval_order", sa.Integer(), nullable=False, server_default="1")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        batch_op.drop_column("approval_order")

    # ### end Alembic commands ###
