"""user invitation and sign in tracking

Both columns are nullable on purpose: an existing user has no invitation and no recorded
sign-in, and inventing one would be a lie the people list then displays.

Revision ID: 2729c746402b
Revises: 73003c6997bf
Create Date: 2026-08-18 21:18:42.892234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2729c746402b"
down_revision: str | Sequence[str] | None = "73003c6997bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("last_signed_in_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_signed_in_at")
        batch_op.drop_column("invited_at")

    # ### end Alembic commands ###
