"""audit events

Revision ID: 8f345a60d72e
Revises: 14feabd416d5
Create Date: 2026-08-23 15:56:22.808355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f345a60d72e"
down_revision: str | Sequence[str] | None = "14feabd416d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_note_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "submitted",
                "approved",
                "rejected",
                "withdrawn",
                "reopened",
                name="auditaction",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("from_state", sa.String(length=16), nullable=False),
        sa.Column("to_state", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["time_note_id"], ["time_notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_time_note_id"), ["time_note_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_time_note_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_id"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
